### ISSUE TITLE
[not bug] android blit type may make snapshot black

### ISSUE THREAD

**Issue by Cm57** [mob-sakai/UIEffectSnapshot#4]
snapshot always show black

1. Set android blit type auto or none
2. Set graphic api to opengles3/2
3. build demo scene

**Expected behavior**
normal blur bg

**Environment (please complete the following information):**
 - Version  1.0.0 
 - Platform: Android
 - Unity version: 2019.4.0f1
 - Build options: blit type auto,opengles3

**Additional context**
Blit and ScreenCapture.CaptureScreenshotIntoRenderTexture neither can get correct color with that setting on android

**Comment by xpc-yx** [comment]
has this bug fixed?

**Comment by Cm57** [comment]
https://issuetracker.unity3d.com/issues/android-the-grabpass-does-not-work-when-the-blit-type-is-set-to-auto
